--Script para alterar las tablas y poder meter los datos

--CANTON
ALTER TABLE CANTON
ADD nombre_provincia nchar(40)

ALTER TABLE CANTON
ALTER COLUMN id_provincia int NULL


--DISTRITO
ALTER TABLE DISTRITO
ADD nombre_canton nchar(40)

ALTER TABLE DISTRITO 
ALTER COLUMN id_canton int NULL


--AFECTADO
ALTER TABLE AFECTADO
ADD nombre_provincia nchar(40)

ALTER TABLE AFECTADO
ADD nombre_canton nchar(40)

ALTER TABLE AFECTADO
ADD nombre_distrito nchar(40)

ALTER TABLE AFECTADO
ADD nombre_dia nchar(20)

ALTER TABLE AFECTADO
ADD nombre_mes nchar(20)

ALTER TABLE AFECTADO
ALTER COLUMN EDAD int NULL

ALTER TABLE AFECTADO 
ALTER COLUMN id_provincia int NULL

ALTER TABLE AFECTADO
ALTER COLUMN id_canton int NULL

ALTER TABLE AFECTADO 
ALTER COLUMN id_distrito int NULL

ALTER TABLE AFECTADO
ALTER COLUMN id_dia int NULL

ALTER TABLE AFECTADO
ALTER COLUMN id_mes int NULL

ALTER TABLE AFECTADO
ALTER COLUMN anho int NULL

ALTER TABLE AFECTADO
ALTER COLUMN id_rol int NULL

ALTER TABLE AFECTADO
ALTER COLUMN id_lesion int NULL

ALTER TABLE AFECTADO
ALTER COLUMN edad_quinquenal nchar(30) NULL

ALTER TABLE AFECTADO
ALTER COLUMN id_sexo int NULL